# Generated by Django 3.1.2 on 2020-10-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='message_phone',
        ),
        migrations.AddField(
            model_name='sender',
            name='message_url',
            field=models.CharField(default='www', max_length=255),
        ),
    ]
