# Generated by Django 3.1.2 on 2020-10-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201023_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='message_phone',
            field=models.IntegerField(default=0),
        ),
    ]
