# Generated by Django 3.1.2 on 2020-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sender_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='message_phone',
            field=models.IntegerField(),
        ),
    ]
