# Generated by Django 3.1.2 on 2020-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201102_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='message_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
