# Generated by Django 3.1.2 on 2020-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201106_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='message_email',
            field=models.EmailField(max_length=255),
        ),
    ]
